version: '3.9'

services:
  node:
    # image: node:16-alpine
    image: todo_app
    build:
      context: ./
      dockerfile: Dockerfile.node
    working_dir: /home/node/app
    command: /bin/sh
    user: ${U:-1000}:${G:-1000}
    tty: true
    stdin_open: true
    stop_signal: SIGKILL
    restart: unless-stopped
    environment:
      PORT: ${PORT:-3000}
    ports:
      - ${PORT:-3002}:${PORT:-3000}
    volumes:
      - ./:/home/node/app
